"use client";
import Layout from "@/layout/Layout";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Suspense, useState, useEffect } from "react";
import Loading from "./loading";
import { Elements } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";
import { CartContext } from "@/context/cartContext";
import { LikeContext } from "@/context/likeContext";

const inter = Inter({ subsets: ["latin"] });

const stripePromise = loadStripe(
  "pk_test_51NXaxvHY1oN4piIiEqXSi3YmrYJTfxkBXikQwJDVN3Jqnng6M4niNp2FzRewFrb0Emsbls2x9x7JcoLOf9cz88IQ00ZXC4iGOj"
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const getCartId: any =
    typeof window !== "undefined" && window.localStorage.getItem("cartId");
  const [cart, setCart] = useState<number[]>(JSON.parse(getCartId));
  const getLikeId: any =
    typeof window !== "undefined" && window.localStorage.getItem("likeId");
  const [like, setLike] = useState<number[]>(JSON.parse(getCartId));
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={`${inter.className}`}>
        <CartContext.Provider value={{ cart, setCart }}>
          <LikeContext.Provider value={{ like, setLike }}>
            <Layout>
              <Elements stripe={stripePromise}>
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </Elements>
            </Layout>
          </LikeContext.Provider>
        </CartContext.Provider>
      </body>
    </html>
  );
}
