"use client"
import Layout from "@/layout/Layout";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Suspense } from "react";
import Loading from "./loading";
import { Elements } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";

const inter = Inter({ subsets: ["latin"] });

const stripePromise = loadStripe(
  "pk_test_51NXaxAAt0rSDCgqM4j2kEZDRFSajHGeMNTvjZIOo8zHcfKqAgEdb8P9Aav5VmSCvCzkLwigfrma9vQQSgtGxtpWC009k1VMTwb"
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <body className={`${inter.className}`}>
        <Layout>
          <Elements stripe={stripePromise}>
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </Elements>
        </Layout>
      </body>
    </html>
  );
}
